name: FirstWorkFlow

on:
   push:
   
   branches:
   - main
   
 jobs:  
    exapmle-job:
      runs-on: ubunto-latest

    steps:
      - name: print weclome message
      run: echo "Wlecome to our first Github Actions workflow"
   
  
 
